* Clojure Solopreneur Meetup
** Meetup 1: Hello, World!

<2024-07-13 Sat>

The first Clojure Solopreneur meetup had 8 participants and lasted
for around 3 hours!

We started with an introduction round where everyone introduced
themselves and what they're working on. Then we ended with some open
conversation.

During the stream a Slack channel [[https://clojurians.slack.com/archives/C07D04A7K7A][#solopreneur]] was created which as of
writing has 19 (!) members 😅. There seems to be a lot of interest so I'm
planning to host a continuation <2024-07-20 Sat> 19:00 UTC. The plan
for that one is TBD so suggestions are greatly appreciated! If anyone
wants to hold a presentation or something, please do say so in the
channel 😄.

I'm writing these notes after the fact, so my memory of each
presentation is so so. I think it's best if each presenter writes
their own summary, so feel free to PR a summary of your intro down
below :^). If you're not familiar with org syntax, just write in plain
text and I will fix any markup issues.

- Olav
  #+begin_quote
  I talked about my SaaS https://anymentions.ai, which is a tool to
  connect startups with the people who's problems they're trying to
  solve. Concretely, it notifies users whenever a post matching a
  given problem description is posted on Reddit.

  AnyMentions originated as an internal tool I built for a previous
  startup saas, we where working on the problem of landlord/tenant
  conflicts, and therefore wanted to reach out to everyone on Reddit
  talking about this. I thought to myself "it wouldn't be too hard to
  build a little Clojure thing to ping us whenever someone posts about
  this" and I had it working within the week.

  Turning it into a proper product is another story entirely 😅
  #+end_quote
